- hosts:
    - all
  become: true
  tags:
    - basic
  roles:
    - init

- hosts:
    - all
  become: true
  tags:
    - auth
  roles:
    - auth

- hosts:
    - vpn
  become: true
  tags:
    - vpn
  roles:
    - resolver
    - openvpn

- hosts:
    - all
  become: true
  tags:
    - reboot
    - basic
    - vpn
    - auth
  roles:
    - remove
    - reboot
