- name: Disable and stop apparmor service
  become: true
  systemd:
    name: apparmor
    enabled: no
    masked: yes
    state: stopped
  tags: apparmor
  ignore_errors: true

- name: Purge packages
  become: true
  apt:
    name: ['apparmor']
    state: absent
    update_cache: yes
