- name: Create /root/bin
  file: dest=/root/bin  state=directory owner=root group={{rootGroup}} mode=0700

- name: Create /root/sbin
  file: dest=/root/sbin state=directory owner=root group={{rootGroup}} mode=0700

- name: Update and upgrade linux packages
  apt:
    upgrade: "yes"
    update_cache: yes
    cache_valid_time: 60
  when: ansible_os_family == 'Debian' or ansible_os_family == 'Ubuntu'

- name: Install packages
  ansible.builtin.package:
    name: ['python3','mc','screen','tcpdump','nmap','psmisc','whois','curl','vim','sudo','ntp','bash','bash-completion','nload','tcptrack','iftop','groff']
    state: present
    autoremove: yes

- name: Install additional linux packages
  ansible.builtin.package:
    name: ['locales-all','aptitude','telnet','traceroute','dnsutils','ethtool','dsniff','apt-transport-https','ca-certificates','software-properties-common','man','gnupg-agent','dstat','net-tools','bsd-mailx','unattended-upgrades']
    state: present
    autoremove: yes
  when: ansible_os_family == 'Debian' or ansible_os_family == 'Ubuntu'

- name: Clean apt
  apt:
    autoremove: yes
    purge: yes
  when: ansible_os_family == 'Debian' or ansible_os_family == 'Ubuntu'

- name: Deploy templates
  template:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    mode: "{{item.mode}}"
    owner: "{{item.owner}}"
    group: "{{item.group}}"
    decrypt: "{{item.decrypt}}"
  with_items:
    - { src: "rc.local.j2", dest: "/etc/rc.local", mode: "0755", owner: "root", group: "{{rootGroup}}", decrypt: "no" }
    - { src: "rc.conf.j2",  dest: "/etc/rc.conf",  mode: "0644", owner: "root", group: "{{rootGroup}}", decrypt: "no" }
